apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
#          hostPort: 9100
          name: scrape
      - name: telegraf
        image: telegraf:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: node-exporter-volume
          mountPath: /etc/telegraf
      volumes:
        - name: node-exporter-volume
          configMap:
            name: telegraf-node-exporter-config
#      hostNetwork: true
      hostPID: true
